sudo: required
services:
  - docker

before_install:
  - docker build -t sikor144/docker-react -f Dockerfile.development .

script:
  - docker run sikor144/docker-react npm run test -- --coverage

deploy:
  provider: "elasticbeanstalk"
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-825461274086"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"